### ISSUE TITLE
compiler v0.5.0+commit and up don't load

### ISSUE THREAD

**Issue by nosequeldeebee** [4c0n/remix-ide-docker#1]
compiler v0.5.0+commit and all later versions hang forever, and don't load. 

![image](https://user-images.githubusercontent.com/15616604/50302689-a9d0e080-043f-11e9-948b-1d8dd3041007.png)

Nightly builds for v0.5.0 and below are ok.

Updating dockerfile to later version of remix should help, though I haven't checked.

**Comment by nosequeldeebee** [comment]
updating remix-ide version to 0.7.5 on https://github.com/4c0n/remix-ide-docker/blob/master/Dockerfile#L20 and rebuilding the docker image fixes the issue

**Comment by 4c0n** [comment]
With which version of this repository are you having problems?

Also when the images were build they were working fine and they haven't changed, so why don't you just pull the image from docker hub?
https://hub.docker.com/r/4c0n/remix-ide/tags

As for releasing a Dockerfile for remix-ide 0.7.4 and 0.7.5, I will look into that once I have some time to test them properly. Feel free to fork this repository and make a pull request if you don't care to wait for that.

**Comment by nosequeldeebee** [comment]
I did pull the image from docker hub. I changed L20 to 0.7.5 and rebuilt the image and it works correctly. Because it's such a simple fix I don't think a PR is necessary :-)

**Comment by 4c0n** [comment]
I'm sorry, but I don't see how releasing a new version solves anything with the existing versions.
What you are describing sounds like a problem with remix ide itself, not necessarily with these images.
I don't have time to look into your issue right now.
I don't consider just changing the remix ide version as a proper fix as you need to match the remixd version with it as well. Otherwise it might not work correctly when we build the image some time from now.

Is there an issue about the compiler version over at the remix ide repository?

**Comment by 4c0n** [comment]
Closing the Issue as the OP has gone quiet. Please re-open it if you feel the need to discuss this any further.
